export const GET_TEAM_COLLABORATOR_LIST = 'GET_TEAM_COLLABORATOR_LIST';
export const GET_TEAM_COLLABORATOR_LIST_SUCCESS =
  'GET_TEAM_COLLABORATOR_LIST_SUCCESS';
export const GET_TEAM_COLLABORATOR_LIST_ERROR =
  'GET_TEAM_COLLABORATOR_LIST_ERROR';
export const GET_TEAM_COLLABORATOR_LIST_CLEAR =
  'GET_TEAM_COLLABORATOR_LIST_CLEAR';
