export const RESET_USER_PASSWORD_CONFIRM = 'RESET_USER_PASSWORD_CONFIRM';
export const RESET_USER_PASSWORD_CONFIRM_SUCCESS =
  'RESET_USER_PASSWORD_CONFIRM_SUCCESS';
export const RESET_USER_PASSWORD_CONFIRM_ERROR =
  'RESET_USER_PASSWORD_CONFIRM_ERROR';
