export const CREATE_NEWS_FEED_COMMENT = 'CREATE_NEWS_FEED_COMMENT';
export const CREATE_NEWS_FEED_COMMENT_SUCCESS =
  'CREATE_NEWS_FEED_COMMENT_SUCCESS';
export const CREATE_NEWS_FEED_COMMENT_ERROR = 'CREATE_NEWS_FEED_COMMENT_ERROR';
export const CREATE_NEWS_FEED_COMMENT_CLEAR = 'CREATE_NEWS_FEED_COMMENT_CLEAR';
