export const GET_GOAL_DEFINITION_LIST = 'GET_GOAL_DEFINITION_LIST';
export const GET_CURRENT_GOAL_DEFINITION_LIST = 'GET_CURRENT_GOAL_DEFINITION_LIST';
export const GET_GOAL_DEFINITION_LIST_SUCCESS = 'GET_GOAL_DEFINITION_LIST_SUCCESS';
export const GET_GOAL_DEFINITION_LIST_ERROR = 'GET_GOAL_DEFINITION_LIST_ERROR';