export const DELETE_WEEK_OVERLAP = 'DELETE_WEEK_OVERLAP';
export const DELETE_WEEK_OVERLAP_SUCCESS = 'DELETE_WEEK_OVERLAP_SUCCESS';
export const DELETE_WEEK_OVERLAP_ERROR = 'DELETE_WEEK_OVERLAP_ERROR';
export const CLEAR_WEEK_OVERLAP_DELETE = 'CLEAR_WEEK_OVERLAP_DELETE';
