export const GET_CURRENT_PERIOD_DETAIL = 'GET_CURRENT_PERIOD_DETAIL';
export const GET_CURRENT_PERIOD_DETAIL_SUCCESS =
  'GET_CURRENT_PERIOD_DETAIL_SUCCESS';
export const GET_CURRENT_PERIOD_DETAIL_ERROR =
  'GET_CURRENT_PERIOD_DETAIL_ERROR';
