export const CREATE_TEAM = 'CREATE_TEAM'
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR'
export const CLEAR_TEAM_CREATION = 'CLEAR_TEAM_CREATION'