export const UPDATE_TEAM_GROUP = 'UPDATE_TEAM_GROUP';
export const UPDATE_TEAM_GROUP_SUCCESS = 'UPDATE_TEAM_GROUP_SUCCESS';
export const UPDATE_TEAM_GROUP_ERROR = 'UPDATE_TEAM_GROUP_ERROR';
export const CLEAR_TEAM_GROUP_UPDATE = 'CLEAR_TEAM_GROUP_UPDATE';
