export const LIKE_NEWS_FEED = 'LIKE_NEWS_FEED';
export const LIKE_NEWS_FEED_SUCCESS = 'LIKE_NEWS_FEED_SUCCESS';
export const LIKE_NEWS_FEED_ERROR = 'LIKE_NEWS_FEED_ERROR';
export const LIKE_NEWS_FEED_CLEAR = 'LIKE_NEWS_FEED_CLEAR';
