export const UPDATE_COLLABORATOR_INPUT = 'UPDATE_COLLABORATOR_INPUT';
export const UPDATE_COLLABORATOR_INPUT_SUCCESS =
  'UPDATE_COLLABORATOR_INPUT_SUCCESS';
export const UPDATE_COLLABORATOR_INPUT_ERROR =
  'UPDATE_COLLABORATOR_INPUT_ERROR';
export const CLEAR_COLLABORATOR_INPUT_UPDATE =
  'CLEAR_COLLABORATOR_INPUT_UPDATE';
