export const GET_ADMIN_REFERENCE_DATA = 'GET_ADMIN_REFERENCE_DATA';
export const GET_ADMIN_REFERENCE_DATA_SUCCESS =
  'GET_ADMIN_REFERENCE_DATA_SUCCESS';
export const GET_ADMIN_REFERENCE_DATA_ERROR = 'GET_ADMIN_REFERENCE_DATA_ERROR';
