export const GET_TEAM_GROUP_TREE = 'GET_TEAM_GROUP_TREE';
export const GET_TEAM_GROUP_TREE_SUCCESS = 'GET_TEAM_GROUP_TREE_SUCCESS';
export const GET_TEAM_GROUP_TREE_ERROR = 'GET_TEAM_GROUP_TREE_ERROR';
