export const GET_NEWS_FEED_LIST = 'GET_NEWS_FEED_LIST';
export const GET_NEWS_FEED_LIST_SUCCESS = 'GET_NEWS_FEED_LIST_SUCCESS';
export const GET_NEWS_FEED_LIST_ERROR = 'GET_NEWS_FEED_LIST_ERROR';
export const GET_NEWS_FEED_LIST_CLEAR = 'GET_NEWS_FEED_LIST_CLEAR';
