image: "node:12.16.1"

stages:
    - build
build:
    stage: build
    script:
        - echo "Building deploy package"
        - yarn
        - CI=false yarn build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build