stages:
    - build
    - deploy
build:
    stage: build
    image: node:latest
    only:
        - master
    script:
        - echo "Building deploy package"
        - yarn
        - npm run-script generate-build-meta
        - CI=false yarn build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
deploy_internal:
    stage: deploy
    image: mwienk/docker-lftp:latest
    only:
        - master
    script:
        - echo "Deploy package"
        - lftp -e "set ftp:ssl-allow false; mirror -eRnv build www/test/firetiger/app; exit;" -u $JORISLENCLUME_FTP_USER,$JORISLENCLUME_FTP_PASSWORD $JORISLENCLUME_FTP_UURL
        - echo "Deploy successful"
