stages:
    - build
    - deploy
build_apptest:
    stage: build
    image: node:latest
    only:
        - release/apptest
    script:
        - echo "Building deploy package"
        - yarn
        - npm run-script generate-build-meta
        - CI=false yarn build
        - CI=false yarn build:external
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
build_app:
    stage: build
    image: node:latest
    only:
        - release/app
    script:
        - echo "Building deploy package"
        - yarn
        - npm run-script generate-build-meta
        - CI=false yarn build
        - echo "Build successful"
    artifacts:
        expire_in: 1 hour
        paths:
            - build
deploy_apptest:
    stage: deploy
    image: mwienk/docker-lftp:latest
    only:
        - release/apptest
    script:
        - echo "Deploy package"
        #        - lftp -e "set ftp:ssl-allow false; mirror -eRnv build www/test/app; exit;" -u firetiger_jorislenclume,F1reT1ger@SSH ftp-firetiger.alwaysdata.net
        - echo "Deploy successful"
deploy_app:
    stage: deploy
    image: mwienk/docker-lftp:latest
    only:
        - release/app
    script:
        - echo "Deploy package"
        #        - lftp -e "set ftp:ssl-allow false; mirror -eRnv build www/production/app; exit;" -u firetiger_jorislenclume,F1reT1ger@SSH ftp-firetiger.alwaysdata.net
        - echo "Deploy successful"
