# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.16.1

pipelines:
  branches:
    master:
      - step:
          name: Build for internal test
          caches:
            - node
          script:
            - npm install
            - npm run-script generate-build-meta
            - CI=false npm run-script build
          artifacts:
            - build/**
      - step:
          name: Clean internal test server
          script:
            - pipe: atlassian/ssh-run:0.2.4
              variables:
                SSH_USER: "jorislenclume"
                SERVER: "ssh-jorislenclume.alwaysdata.net"
                COMMAND: "rm -rf www/test/firetiger/app/*"
      - step:
          name: Deploy to internal test
          deployment: test
          script:
            - echo "Deploying to test environment"
            - pipe: atlassian/scp-deploy:0.3.10
              variables:
                USER: "jorislenclume"
                SERVER: "ssh-jorislenclume.alwaysdata.net"
                REMOTE_PATH: "www/test/firetiger/app/"
                LOCAL_PATH: "build/*"
