# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.16.1

pipelines:
  branches:
    master:
      - step:
          name: Build for internal test
          caches:
            - node
          script:
            - npm install
            - CI=false npm run-script build
            - mkdir packaged
            - tar -czvf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C build .
          artifacts:
            - packaged/**
      - step:
          name: Deploy to internal test
          deployment: test
          script:
            - echo "Deploying to test environment"
      - step:
          name: Deploy notification for internal test
          script:
            - pipe: atlassian/email-notify:0.3.9
              variables:
                USERNAME: "jorislenclume@alwaysdata.net"
                PASSWORD: "J0r1s@dev"
                FROM: "no-reply@jorislenclume.com"
                TO: "jlenclume@icloud.com"
                HOST: "smtp-jorislenclume.alwaysdata.net"
                PORT: "25"
                TLS: "false"
                SUBJECT: "[Message automatique] Notification de mise à jour"
