# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.16.1

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - pwd
          - ls -al
          - npm install
          - CI=false npm run-script build
          - mkdir packaged
          - tar -czvf packaged/package-${BITBUCKET_BUILD_NUMBER}.tar.gz -C build .
        artifacts:
          - packaged/**
    - step:
        name: Deploy to test
        deployment: test
        script:
          - echo "Deploying to test environment"
