image: node:12.16.1

pipelines:
  branches:
    master:
      - step:
          name: Deploy to internal test
          deployment: test
          script:
             - pipe: atlassian/ssh-run:0.2.4
               variables:
                 SSH_USER: "jorislenclume"
                 SERVER: "ssh-jorislenclume.alwaysdata.net"
                 COMMAND: "yarn"
