services:
  objow-web-app:
    container_name: objow-web-app
    build: .
    ports:
      - "${OBJOW_WEB_APP_PORT}:${OBJOW_WEB_APP_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - objow-network

networks:
  objow-network:
    external: true
