export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR'
export const CLEAR_ACCOUNT_UPDATE = 'CLEAR_ACCOUNT_UPDATE'
