export const GET_CONFIG_LIST = 'GET_CONFIG_LIST';
export const GET_PERMANENT_CONFIG_LIST = 'GET_PERMANENT_CONFIG_LIST';
export const GET_CONFIG_LIST_SUCCESS = 'GET_CONFIG_LIST_SUCCESS';
export const GET_CONFIG_LIST_ERROR = 'GET_CONFIG_LIST_ERROR';
export const CLEAR_CONFIG_LIST = 'CLEAR_CONFIG_LIST';
