export const GET_TEAM_GOAL_LIST_BY_DEFINITION =
  'GET_TEAM_GOAL_LIST_BY_DEFINITION';
export const GET_TEAM_GOAL_LIST_SUCCESS = 'GET_TEAM_GOAL_LIST_SUCCESS';
export const GET_TEAM_GOAL_LIST_ERROR = 'GET_TEAM_GOAL_LIST_ERROR';
