export const CREATE_REWARD = 'CREATE_REWARD'
export const CREATE_REWARD_SUCCESS = 'CREATE_REWARD_SUCCESS'
export const CREATE_REWARD_ERROR = 'CREATE_REWARD_ERROR'
export const CLEAR_REWARD_CREATION = 'CLEAR_REWARD_CREATION'
