export const GET_COLLABORATOR_DETAIL = 'GET_COLLABORATOR_DETAIL'
export const GET_COLLABORATOR_DETAIL_SUCCESS = 'GET_COLLABORATOR_DETAIL_SUCCESS'
export const GET_COLLABORATOR_DETAIL_ERROR = 'GET_COLLABORATOR_DETAIL_ERROR'