export const GET_CHALLENGE_PARTICIPANT_LIST = 'GET_CHALLENGE_PARTICIPANT_LIST';
export const GET_CHALLENGE_PARTICIPANT_COLLABORATOR_LIST =
  'GET_CHALLENGE_PARTICIPANT_COLLABORATOR_LIST';
export const GET_CHALLENGE_PARTICIPANT_LIST_SUCCESS =
  'GET_CHALLENGE_PARTICIPANT_LIST_SUCCESS';
export const GET_CHALLENGE_PARTICIPANT_LIST_ERROR =
  'GET_CHALLENGE_PARTICIPANT_LIST_ERROR';
