export const UPDATE_PLAYER_GOAL_LIST = 'UPDATE_PLAYER_GOAL_LIST'
export const UPDATE_PLAYER_GOAL_LIST_SUCCESS = 'UPDATE_PLAYER_GOAL_LIST_SUCCESS'
export const UPDATE_PLAYER_GOAL_LIST_ERROR = 'UPDATE_PLAYER_GOAL_LIST_ERROR'