export const IMPORT_USER_LIST = 'IMPORT_USER_LIST';
export const IMPORT_USER_LIST_SUCCESS = 'IMPORT_USER_LIST_SUCCESS';
export const IMPORT_USER_LIST_ERROR = 'IMPORT_USER_LIST_ERROR';
export const CLEAR_USER_LIST_IMPORT = 'CLEAR_USER_LIST_IMPORT';
