export const UPDATE_USER_ACTIVATION = 'UPDATE_USER_ACTIVATION';
export const UPDATE_USER_ACTIVATION_SUCCESS = 'UPDATE_USER_ACTIVATION_SUCCESS';
export const UPDATE_USER_ACTIVATION_ERROR = 'UPDATE_USER_ACTIVATION_ERROR';
export const CLEAR_USER_ACTIVATION_UPDATE = 'CLEAR_USER_ACTIVATION_UPDATE';