export const CREATE_GOAL_DEFINITION = 'CREATE_GOAL_DEFINITION';
export const CREATE_GOAL_DEFINITION_SUCCESS = 'CREATE_GOAL_DEFINITION_SUCCESS';
export const CREATE_GOAL_DEFINITION_ERROR = 'CREATE_GOAL_DEFINITION_ERROR';
export const CLEAR_GOAL_DEFINITION_CREATION = 'CLEAR_GOAL_DEFINITION_CREATION';
