export const GET_COLLABORATOR_REWARD_LIST = 'GET_COLLABORATOR_REWARD_LIST'
export const GET_REWARD_LIST_SUCCESS = 'GET_REWARD_LIST_SUCCESS'
export const GET_REWARD_LIST_ERROR = 'GET_REWARD_LIST_ERROR'
