export const GET_MANAGER_GOAL_LIST = 'GET_MANAGER_GOAL_LIST';
export const GET_MANAGER_GOAL_LIST_SUCCESS = 'GET_MANAGER_GOAL_LIST_SUCCESS';
export const GET_MANAGER_GOAL_LIST_ERROR = 'GET_MANAGER_GOAL_LIST_ERROR';
