export const GET_TEAM_CHALLENGE_LIST_BY_COLLABORATOR = 'GET_TEAM_CHALLENGE_LIST_BY_COLLABORATOR';
export const GET_TEAM_CHALLENGE_LIST_BY_TEAM = 'GET_TEAM_CHALLENGE_LIST_BY_TEAM';
export const GET_TEAM_CHALLENGE_LIST_SUCCESS = 'GET_TEAM_CHALLENGE_LIST_SUCCESS';
export const GET_TEAM_CHALLENGE_LIST_ERROR = 'GET_TEAM_CHALLENGE_LIST_ERROR';