export const REMOVE_TEAM_GROUP = 'REMOVE_TEAM_GROUP';
export const REMOVE_TEAM_GROUP_SUCCESS = 'REMOVE_TEAM_GROUP_SUCCESS';
export const REMOVE_TEAM_GROUP_ERROR = 'REMOVE_TEAM_GROUP_ERROR';
export const CLEAR_TEAM_GROUP_REMOVING = 'CLEAR_TEAM_GROUP_REMOVING';
