export const GET_REWARD_IMAGE_LIST = 'GET_REWARD_IMAGE_LIST';
export const GET_REWARD_IMAGE_LIST_SUCCESS = 'GET_REWARD_IMAGE_LIST_SUCCESS';
export const GET_REWARD_IMAGE_LIST_ERROR = 'GET_REWARD_IMAGE_LIST_ERROR';
