export const GET_VALIDATED_TEAM_REWARD_ORDER_SUMMARY_LIST =
  'GET_VALIDATED_TEAM_REWARD_ORDER_SUMMARY_LIST';
export const GET_WAITING_TEAM_REWARD_ORDER_SUMMARY_LIST =
  'GET_WAITING_TEAM_REWARD_ORDER_SUMMARY_LIST';
export const GET_TEAM_REWARD_ORDER_SUMMARY_LIST_SUCCESS =
  'GET_TEAM_REWARD_ORDER_SUMMARY_LIST_SUCCESS';
export const GET_TEAM_REWARD_ORDER_SUMMARY_LIST_ERROR =
  'GET_TEAM_REWARD_ORDER_SUMMARY_LIST_ERROR';
