export const REMOVE_COACHING_ITEM = 'REMOVE_COACHING_ITEM';
export const REMOVE_COACHING_ITEM_SUCCESS = 'REMOVE_COACHING_ITEM_SUCCESS';
export const REMOVE_COACHING_ITEM_ERROR = 'REMOVE_COACHING_ITEM_ERROR';
