export const GET_TEAM_REWARD_ORDER = 'GET_TEAM_REWARD_ORDER'
export const GET_TEAM_REWARD_ORDER_SUCCESS = 'GET_TEAM_REWARD_ORDER_SUCCESS'
export const GET_TEAM_REWARD_ORDER_ERROR = 'GET_TEAM_REWARD_ORDER_ERROR'
export const CLEAR_TEAM_REWARD_ORDER_DETAIL = 'CLEAR_TEAM_REWARD_ORDER_DETAIL'
