export const GET_GOAL_ADVICE_LIST_BY_COLLABORATOR_GOAL = 'GET_GOAL_ADVICE_LIST_BY_COLLABORATOR_GOAL';
export const GET_GOAL_ADVICE_LIST_BY_TEAM_COLLABORATOR_GOAL = 'GET_GOAL_ADVICE_LIST_BY_TEAM_COLLABORATOR_GOAL';
export const GET_GOAL_ADVICE_LIST_BY_TEAM_GOAL = 'GET_GOAL_ADVICE_LIST_BY_TEAM_GOAL';
export const GET_GOAL_ADVICE_LIST_SUCCESS = 'GET_GOAL_ADVICE_LIST_SUCCESS';
export const GET_GOAL_ADVICE_LIST_ERROR = 'GET_GOAL_ADVICE_LIST_ERROR';
