export const GET_TEAM_GOAL_RANK_LIST = 'GET_TEAM_GOAL_RANK_LIST';
export const GET_TEAM_GOAL_RANK_LIST_SUCCESS =
  'GET_TEAM_GOAL_RANK_LIST_SUCCESS';
export const GET_TEAM_GOAL_RANK_LIST_ERROR = 'GET_TEAM_GOAL_RANK_LIST_ERROR';
