export const GET_IN_APP_NOTIFICATION_LIST = 'GET_IN_APP_NOTIFICATION_LIST';
export const GET_IN_APP_NOTIFICATION_LIST_SUCCESS =
  'GET_IN_APP_NOTIFICATION_LIST_SUCCESS';
export const GET_IN_APP_NOTIFICATION_LIST_ERROR =
  'GET_IN_APP_NOTIFICATION_LIST_ERROR';
