export const GET_PREVIOUS_PERIOD_LIST = 'GET_PREVIOUS_PERIOD_LIST';
export const GET_PREVIOUS_PERIOD_LIST_SUCCESS = 'GET_PREVIOUS_PERIOD_LIST_SUCCESS';
export const GET_PREVIOUS_PERIOD_LIST_ERROR = 'GET_PREVIOUS_PERIOD_LIST_ERROR';