export const GET_IMPORT_USERS_LOG_LIST = 'GET_IMPORT_USERS_LOG_LIST';
export const GET_IMPORT_USERS_LOG_LIST_SUCCESS =
  'GET_IMPORT_USERS_LOG_LIST_SUCCESS';
export const GET_IMPORT_USERS_LOG_LIST_ERROR =
  'GET_IMPORT_USERS_LOG_LIST_ERROR';
