export const GET_WEEK_OVERLAP_LIST = 'GET_WEEK_OVERLAP_LIST';
export const GET_WEEK_OVERLAP_LIST_SUCCESS = 'GET_WEEK_OVERLAP_LIST_SUCCESS';
export const GET_WEEK_OVERLAP_LIST_ERROR = 'GET_WEEK_OVERLAP_LIST_ERROR';
