export const UPDATE_COLLABORATOR_DATA = 'UPDATE_COLLABORATOR_DATA'
export const UPDATE_COLLABORATOR_DATA_SUCCESS = 'UPDATE_COLLABORATOR_DATA_SUCCESS'
export const UPDATE_COLLABORATOR_DATA_ERROR = 'UPDATE_COLLABORATOR_DATA_ERROR'
export const CLEAR_COLLABORATOR_DATA_UPDATE = 'CLEAR_COLLABORATOR_DATA_UPDATE'