export const GET_KPI_DETAIL = 'GET_KPI_DETAIL';
export const GET_KPI_DETAIL_SUCCESS = 'GET_KPI_DETAIL_SUCCESS';
export const GET_KPI_DETAIL_ERROR = 'GET_KPI_DETAIL_ERROR';
export const GET_KPI_DETAIL_CLEAR = 'GET_KPI_DETAIL_CLEAR';
