export const GET_PERIODICITY_LIST = 'GET_PERIODICITY_LIST';
export const GET_PERIODICITY_LIST_SUCCESS = 'GET_PERIODICITY_LIST_SUCCESS';
export const GET_PERIODICITY_LIST_ERROR = 'GET_PERIODICITY_LIST_ERROR';
