export const LIKE_NEWS_FEED_COMMENT = 'LIKE_NEWS_FEED_COMMENT';
export const LIKE_NEWS_FEED_COMMENT_SUCCESS = 'LIKE_NEWS_FEED_COMMENT_SUCCESS';
export const LIKE_NEWS_FEED_COMMENT_ERROR = 'LIKE_NEWS_FEED_COMMENT_ERROR';
export const LIKE_NEWS_FEED_COMMENT_CLEAR = 'LIKE_NEWS_FEED_COMMENT_CLEAR';
