export const CREATE_LEVEL_LIST = 'CREATE_LEVEL_LIST';
export const CREATE_LEVEL_LIST_SUCCESS = 'CREATE_LEVEL_LIST_SUCCESS';
export const CREATE_LEVEL_LIST_ERROR = 'CREATE_LEVEL_LIST_ERROR';
export const CLEAR_LEVEL_LIST_CREATION = 'CLEAR_LEVEL_LIST_CREATION';
