export const GET_PLAYER_GOAL_LIST = 'GET_PLAYER_GOAL_LIST';
export const GET_PLAYER_GOAL_LIST_SUCCESS = 'GET_PLAYER_GOAL_LIST_SUCCESS';
export const GET_PLAYER_GOAL_LIST_ERROR = 'GET_PLAYER_GOAL_LIST_ERROR';
