export const UPDATE_SYSTEM_IMAGE = 'UPDATE_SYSTEM_IMAGE'
export const UPDATE_SYSTEM_IMAGE_SUCCESS = 'UPDATE_SYSTEM_IMAGE_SUCCESS'
export const UPDATE_SYSTEM_IMAGE_ERROR = 'UPDATE_SYSTEM_IMAGE_ERROR'
export const CLEAR_SYSTEM_IMAGE_UPDATE = 'CLEAR_SYSTEM_IMAGE_UPDATE'