export const GET_CHALLENGE_IMAGE_LIST = 'GET_CHALLENGE_IMAGE_LIST'
export const GET_CHALLENGE_IMAGE_LIST_SUCCESS = 'GET_CHALLENGE_IMAGE_LIST_SUCCESS'
export const GET_CHALLENGE_IMAGE_LIST_ERROR = 'GET_CHALLENGE_IMAGE_LIST_ERROR'