export const CREATE_NEWS_FEED = 'CREATE_NEWS_FEED';
export const CREATE_NEWS_FEED_SUCCESS = 'CREATE_NEWS_FEED_SUCCESS';
export const CREATE_NEWS_FEED_ERROR = 'CREATE_NEWS_FEED_ERROR';
export const CREATE_NEWS_FEED_CLEAR = 'CREATE_NEWS_FEED_CLEAR';
