export const GET_SYSTEM_IMAGE_LIST = 'GET_SYSTEM_IMAGE_LIST'
export const GET_SYSTEM_IMAGE_LIST_SUCCESS = 'GET_SYSTEM_IMAGE_LIST_SUCCESS'
export const GET_SYSTEM_IMAGE_LIST_ERROR = 'GET_SYSTEM_IMAGE_LIST_ERROR'