export const GET_CHALLENGE_AWARD_TYPE_LIST = 'GET_CHALLENGE_AWARD_TYPE_LIST';
export const GET_CHALLENGE_AWARD_TYPE_LIST_SUCCESS =
  'GET_CHALLENGE_AWARD_TYPE_LIST_SUCCESS';
export const GET_CHALLENGE_AWARD_TYPE_LIST_ERROR =
  'GET_CHALLENGE_AWARD_TYPE_LIST_ERROR';
