export const UPDATE_CONFIG_LIST = 'UPDATE_CONFIG_LIST'
export const UPDATE_CONFIG_LIST_SUCCESS = 'UPDATE_CONFIG_LIST_SUCCESS'
export const UPDATE_CONFIG_LIST_ERROR = 'UPDATE_CONFIG_LIST_ERROR'
export const CLEAR_CONFIG_LIST_UPDATE = 'CLEAR_CONFIG_LIST_UPDATE'