export const GET_MENU_NOTIFICATION_LIST = 'GET_MENU_NOTIFICATION_LIST';
export const GET_MENU_NOTIFICATION_LIST_SUCCESS =
  'GET_MENU_NOTIFICATION_LIST_SUCCESS';
export const GET_MENU_NOTIFICATION_LIST_ERROR =
  'GET_MENU_NOTIFICATION_LIST_ERROR';
