export const GET_CHALLENGE_TYPE_SUMMARY_LIST =
  'GET_CHALLENGE_TYPE_SUMMARY_LIST';
export const GET_CHALLENGE_TYPE_SUMMARY_LIST_SUCCESS =
  'GET_CHALLENGE_TYPE_SUMMARY_LIST_SUCCESS';
export const GET_CHALLENGE_TYPE_SUMMARY_LIST_ERROR =
  'GET_CHALLENGE_TYPE_SUMMARY_LIST_ERROR';
