export const GET_COLLABORATOR_REWARD_ORDER = 'GET_COLLABORATOR_REWARD_ORDER';
export const GET_COLLABORATOR_REWARD_ORDER_SUCCESS =
  'GET_COLLABORATOR_REWARD_ORDER_SUCCESS';
export const GET_COLLABORATOR_REWARD_ORDER_ERROR =
  'GET_COLLABORATOR_REWARD_ORDER_ERROR';
export const CLEAR_COLLABORATOR_REWARD_ORDER_DETAIL =
  'CLEAR_COLLABORATOR_REWARD_ORDER_DETAIL';
