export const GET_COLLABORATOR_CHALLENGE_LIST =
  'GET_COLLABORATOR_CHALLENGE_LIST';
export const GET_COLLABORATOR_CHALLENGE_LIST_SUCCESS =
  'GET_COLLABORATOR_CHALLENGE_LIST_SUCCESS';
export const GET_COLLABORATOR_CHALLENGE_LIST_ERROR =
  'GET_COLLABORATOR_CHALLENGE_LIST_ERROR';
export const GET_COLLABORATOR_CHALLENGE_LIST_CLEAR =
  'GET_COLLABORATOR_CHALLENGE_LIST_CLEAR';
