export const GET_ACTIVE_REWARD_CATEGORY_LIST =
  'GET_ACTIVE_REWARD_CATEGORY_LIST';
export const GET_INACTIVE_REWARD_CATEGORY_LIST =
  'GET_INACTIVE_REWARD_CATEGORY_LIST';
export const GET_REWARD_CATEGORY_LIST_SUCCESS =
  'GET_REWARD_CATEGORY_LIST_SUCCESS';
export const GET_REWARD_CATEGORY_LIST_ERROR = 'GET_REWARD_CATEGORY_LIST_ERROR';
