export const UPDATE_GOAL_DEFINITION = 'UPDATE_GOAL_DEFINITION';
export const UPDATE_GOAL_DEFINITION_SUCCESS = 'UPDATE_GOAL_DEFINITION_SUCCESS';
export const UPDATE_GOAL_DEFINITION_ERROR = 'UPDATE_GOAL_DEFINITION_ERROR';
export const CLEAR_GOAL_DEFINITION_UPDATE = 'CLEAR_GOAL_DEFINITION_UPDATE';
