export const GET_COLLABORATOR_GLOBAL_POINT_SUMMARY =
  'GET_COLLABORATOR_GLOBAL_POINT_SUMMARY';
export const GET_COLLABORATOR_GLOBAL_POINT_SUMMARY_SUCCESS =
  'GET_COLLABORATOR_GLOBAL_POINT_SUMMARY_SUCCESS';
export const GET_COLLABORATOR_GLOBAL_POINT_SUMMARY_ERROR =
  'GET_COLLABORATOR_GLOBAL_POINT_SUMMARY_ERROR';
