export const CREATE_TEAM_REWARD_ORDER = 'CREATE_TEAM_REWARD_ORDER';
export const CREATE_TEAM_REWARD_ORDER_SUCCESS =
  'CREATE_TEAM_REWARD_ORDER_SUCCESS';
export const CREATE_TEAM_REWARD_ORDER_ERROR = 'CREATE_TEAM_REWARD_ORDER_ERROR';
export const CLEAR_TEAM_REWARD_ORDER_CREATION =
  'CLEAR_TEAM_REWARD_ORDER_CREATION';
