export const GET_COLLABORATOR_GOAL_CATEGORY_LIST =
  'GET_COLLABORATOR_GOAL_CATEGORY_LIST';
export const GET_COLLABORATOR_GOAL_CATEGORY_LIST_SUCCESS =
  'GET_COLLABORATOR_GOAL_CATEGORY_LIST_SUCCESS';
export const GET_COLLABORATOR_GOAL_CATEGORY_LIST_ERROR =
  'GET_COLLABORATOR_GOAL_CATEGORY_LIST_ERROR';
