export const CREATE_CHALLENGE = 'CREATE_CHALLENGE';
export const CREATE_CHALLENGE_SUCCESS = 'CREATE_CHALLENGE_SUCCESS';
export const CREATE_CHALLENGE_ERROR = 'CREATE_CHALLENGE_ERROR';
export const CLEAR_CHALLENGE_CREATION = 'CLEAR_CHALLENGE_CREATION';