export const GET_ACTIVE_CATEGORY_LIST = 'GET_ACTIVE_CATEGORY_LIST';
export const GET_INACTIVE_CATEGORY_LIST = 'GET_INACTIVE_CATEGORY_LIST';
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS';
export const GET_CATEGORY_LIST_ERROR = 'GET_CATEGORY_LIST_ERROR';
