export const UPDATE_CONFIG = 'UPDATE_CONFIG'
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS'
export const UPDATE_CONFIG_ERROR = 'UPDATE_CONFIG_ERROR'
export const CLEAR_CONFIG_UPDATE = 'CLEAR_CONFIG_UPDATE'