export const UPDATE_REWARD_CATEGORY = 'UPDATE_REWARD_CATEGORY';
export const UPDATE_REWARD_CATEGORY_ACTIVATION =
  'UPDATE_REWARD_CATEGORY_ACTIVATION';
export const UPDATE_REWARD_CATEGORY_SUCCESS = 'UPDATE_REWARD_CATEGORY_SUCCESS';
export const UPDATE_REWARD_CATEGORY_ERROR = 'UPDATE_REWARD_CATEGORY_ERROR';
export const CLEAR_REWARD_CATEGORY_UPDATE = 'CLEAR_REWARD_CATEGORY_UPDATE';
