export const DELETE_NEWS_FEED = 'DELETE_NEWS_FEED';
export const DELETE_NEWS_FEED_SUCCESS = 'DELETE_NEWS_FEED_SUCCESS';
export const DELETE_NEWS_FEED_ERROR = 'DELETE_NEWS_FEED_ERROR';
export const DELETE_NEWS_FEED_CLEAR = 'DELETE_NEWS_FEED_CLEAR';
