export const UPDATE_COACHING_ITEM_LIST = 'UPDATE_COACHING_ITEM_LIST';
export const UPDATE_COACHING_ITEM_LIST_SUCCESS =
  'UPDATE_COACHING_ITEM_LIST_SUCCESS';
export const UPDATE_COACHING_ITEM_LIST_ERROR =
  'UPDATE_COACHING_ITEM_LIST_ERROR';
export const UPDATE_COACHING_ITEM_LIST_CLEAR =
  'UPDATE_COACHING_ITEM_LIST_CLEAR';
