export const GET_LEVELS_USABLE_LIST = `GET_LEVELS_USABLE_LIST`;
export const GET_USABLE_LIST_FOR_LEVEL = `GET_USABLE_LIST_FOR_LEVEL`;
export const GET_LEVEL_ICON_LIST_SUCCESS = 'GET_LEVEL_ICON_LIST_SUCCESS';
export const GET_LEVEL_ICON_LIST_ERROR = 'GET_LEVEL_ICON_LIST_ERROR';
