export const UPDATE_BADGE_LEVEL_LIST = 'UPDATE_BADGE_LEVEL_LIST'
export const UPDATE_BADGE_LEVEL_LIST_SUCCESS = 'UPDATE_BADGE_LEVEL_LIST_SUCCESS'
export const UPDATE_BADGE_LEVEL_LIST_ERROR = 'UPDATE_BADGE_LEVEL_LIST_ERROR'
export const CLEAR_BADGE_LEVEL_LIST_UPDATE = 'CLEAR_BADGE_LEVEL_LIST_UPDATE'