export const GET_FREE_SUPER_MANAGER_LIST = 'GET_FREE_SUPER_MANAGER_LIST';
export const GET_SUPER_MANAGER_LIST_SUCCESS = 'GET_SUPER_MANAGER_LIST_SUCCESS';
export const GET_SUPER_MANAGER_LIST_ERROR = 'GET_SUPER_MANAGER_LIST_ERROR';
