export const GET_BADGE_LEVEL_REMAINING_POINTS =
  'GET_BADGE_LEVEL_REMAINING_POINTS';
export const GET_BADGE_LEVEL_REMAINING_POINTS_SUCCESS =
  'GET_BADGE_LEVEL_REMAINING_POINTS_SUCCESS';
export const GET_BADGE_LEVEL_REMAINING_POINTS_ERROR =
  'GET_BADGE_LEVEL_REMAINING_POINTS_ERROR';
