export const GET_TEAM_GOAL_CATEGORY_LIST = 'GET_TEAM_GOAL_CATEGORY_LIST';
export const GET_TEAM_GOAL_CATEGORY_LIST_SUCCESS =
  'GET_TEAM_GOAL_CATEGORY_LIST_SUCCESS';
export const GET_TEAM_GOAL_CATEGORY_LIST_ERROR =
  'GET_TEAM_GOAL_CATEGORY_LIST_ERROR';
