export const GET_USABLE_LIST = `GET_USABLE_LIST`;
export const GET_USABLE_LIST_FOR_BADGE = `GET_USABLE_LIST_FOR_BADGE`;
export const GET_BADGE_ICON_LIST_SUCCESS = 'GET_BADGE_ICON_LIST_SUCCESS';
export const GET_BADGE_ICON_LIST_ERROR = 'GET_BADGE_ICON_LIST_ERROR';
