export const GET_USER_IDENTIFIER_LIST = 'GET_USER_IDENTIFIER_LIST';
export const GET_USER_IDENTIFIER_LIST_SUCCESS =
  'GET_USER_IDENTIFIER_LIST_SUCCESS';
export const GET_USER_IDENTIFIER_LIST_ERROR = 'GET_USER_IDENTIFIER_LIST_ERROR';
export const GET_USER_IDENTIFIER_LIST_CLEAR = 'GET_USER_IDENTIFIER_LIST_CLEAR';
