export const UPDATE_TEAM_PLAYER_GOAL_LIST = 'UPDATE_TEAM_PLAYER_GOAL_LIST';
export const UPDATE_TEAM_PLAYER_GOAL_LIST_SUCCESS =
  'UPDATE_TEAM_PLAYER_GOAL_LIST_SUCCESS';
export const UPDATE_TEAM_PLAYER_GOAL_LIST_ERROR =
  'UPDATE_TEAM_PLAYER_GOAL_LIST_ERROR';
export const UPDATE_TEAM_PLAYER_GOAL_LIST_CLEAR =
  'UPDATE_TEAM_PLAYER_GOAL_LIST_CLEAR';
