export const CREATE_REWARD_CATEGORY = 'CREATE_REWARD_CATEGORY';
export const CREATE_REWARD_CATEGORY_SUCCESS = 'CREATE_REWARD_CATEGORY_SUCCESS';
export const CREATE_REWARD_CATEGORY_ERROR = 'CREATE_REWARD_CATEGORY_ERROR';
export const CLEAR_REWARD_CATEGORY_CREATION = 'CLEAR_REWARD_CATEGORY_CREATION';
