export const CREATE_COLLABORATOR_INPUT = 'CREATE_COLLABORATOR_INPUT';
export const CREATE_COLLABORATOR_INPUT_SUCCESS =
  'CREATE_COLLABORATOR_INPUT_SUCCESS';
export const CREATE_COLLABORATOR_INPUT_ERROR =
  'CREATE_COLLABORATOR_INPUT_ERROR';
export const CLEAR_COLLABORATOR_INPUT_CREATION =
  'CLEAR_COLLABORATOR_INPUT_CREATION';
