export const DELETE_CHALLENGE = 'DELETE_CHALLENGE';
export const DELETE_CHALLENGE_SUCCESS = 'DELETE_CHALLENGE_SUCCESS';
export const DELETE_CHALLENGE_ERROR = 'DELETE_CHALLENGE_ERROR';
export const CLEAR_CHALLENGE_DELETE = 'CLEAR_CHALLENGE_DELETE';
