export const GET_CHALLENGE_TYPE_LIST = 'GET_CHALLENGE_TYPE_LIST';
export const GET_CURRENT_CHALLENGE_TYPE_LIST =
  'GET_CURRENT_CHALLENGE_TYPE_LIST';
export const GET_USABLE_CHALLENGE_TYPE_LIST = 'GET_USABLE_CHALLENGE_TYPE_LIST';
export const GET_CHALLENGE_TYPE_LIST_SUCCESS =
  'GET_CHALLENGE_TYPE_LIST_SUCCESS';
export const GET_CHALLENGE_TYPE_LIST_ERROR = 'GET_CHALLENGE_TYPE_LIST_ERROR';
