export const GET_TEAM_DETAIL = 'GET_TEAM_DETAIL';
export const GET_TEAM_DETAIL_BY_ACCOOUNT = 'GET_TEAM_DETAIL_BY_ACCOOUNT';
export const GET_TEAM_DETAIL_SUCCESS = 'GET_TEAM_DETAIL_SUCCESS';
export const GET_TEAM_DETAIL_ERROR = 'GET_TEAM_DETAIL_ERROR';
export const CLEAR_TEAM_DETAIL = 'CLEAR_TEAM_DETAIL';
