export const REMOVE_BADGE_LEVEL_LIST = 'REMOVE_BADGE_LEVEL_LIST';
export const REMOVE_BADGE_LEVEL_LIST_SUCCESS = 'REMOVE_BADGE_LEVEL_LIST_SUCCESS';
export const REMOVE_BADGE_LEVEL_LIST_ERROR = 'REMOVE_BADGE_LEVEL_LIST_ERROR';
export const CLEAR_BADGE_LEVEL_LIST_REMOVING = 'CLEAR_BADGE_LEVEL_LIST_REMOVING';
