export const UPDATE_CHALLENGE = 'UPDATE_CHALLENGE';
export const UPDATE_CHALLENGE_SUCCESS = 'UPDATE_CHALLENGE_SUCCESS';
export const UPDATE_CHALLENGE_ERROR = 'UPDATE_CHALLENGE_ERROR';
export const CLEAR_CHALLENGE_UPDATE = 'CLEAR_CHALLENGE_UPDATE';
