export const UPDATE_CATEGORY_ACTIVATION = 'UPDATE_CATEGORY_ACTIVATION';
export const UPDATE_CATEGORY_ACTIVATION_SUCCESS = 'UPDATE_CATEGORY_ACTIVATION_SUCCESS';
export const UPDATE_CATEGORY_ACTIVATION_ERROR = 'UPDATE_CATEGORY_ACTIVATION_ERROR';
export const CLEAR_CATEGORY_ACTIVATION_UPDATE = 'CLEAR_CATEGORY_ACTIVATION_UPDATE';
