export const GET_KPI_LIST = 'GET_KPI_LIST';
export const GET_KPI_LIST_BY_PARTNER = 'GET_KPI_LIST_BY_PARTNER';
export const GET_KPI_LIST_SUCCESS = 'GET_KPI_LIST_SUCCESS';
export const GET_KPI_LIST_ERROR = 'GET_KPI_LIST_ERROR';
