export const REPORT_NEWS_FEED = 'REPORT_NEWS_FEED';
export const REPORT_NEWS_FEED_SUCCESS = 'REPORT_NEWS_FEED_SUCCESS';
export const REPORT_NEWS_FEED_ERROR = 'REPORT_NEWS_FEED_ERROR';
export const REPORT_NEWS_FEED_CLEAR = 'REPORT_NEWS_FEED_CLEAR';
