export const UPDATE_TEAM_REWARD_ORDER = 'UPDATE_TEAM_REWARD_ORDER';
export const UPDATE_TEAM_REWARD_ORDER_SUCCESS =
  'UPDATE_TEAM_REWARD_ORDER_SUCCESS';
export const UPDATE_TEAM_REWARD_ORDER_ERROR = 'UPDATE_TEAM_REWARD_ORDER_ERROR';
export const CLEAR_TEAM_REWARD_ORDER_UPDATE = 'CLEAR_TEAM_REWARD_ORDER_UPDATE';
