export const REPORT_NEWS_FEED_COMMENT = 'REPORT_NEWS_FEED_COMMENT';
export const REPORT_NEWS_FEED_COMMENT_SUCCESS =
  'REPORT_NEWS_FEED_COMMENT_SUCCESS';
export const REPORT_NEWS_FEED_COMMENT_ERROR = 'REPORT_NEWS_FEED_COMMENT_ERROR';
export const REPORT_NEWS_FEED_COMMENT_CLEAR = 'REPORT_NEWS_FEED_COMMENT_CLEAR';
