export const GET_TEAM_GOAL_BULK_LIST = 'GET_TEAM_GOAL_BULK_LIST';
export const GET_TEAM_GOAL_BULK_LIST_SUCCESS =
  'GET_TEAM_GOAL_BULK_LIST_SUCCESS';
export const GET_TEAM_GOAL_BULK_LIST_ERROR = 'GET_TEAM_GOAL_BULK_LIST_ERROR';
export const GET_TEAM_GOAL_BULK_LIST_CLEAR = 'GET_TEAM_GOAL_BULK_LIST_CLEAR';
