export const GET_REWARD_TYPE_LIST = 'GET_REWARD_TYPE_LIST';
export const GET_REWARD_TYPE_LIST_SUCCESS = 'GET_REWARD_TYPE_LIST_SUCCESS';
export const GET_REWARD_TYPE_LIST_ERROR = 'GET_REWARD_TYPE_LIST_ERROR';
