export const GET_COLLABORATOR_DATA_LIST = 'GET_COLLABORATOR_DATA';
export const GET_COLLABORATOR_DATA_LIST_SUCCESS =
  'GET_COLLABORATOR_DATA_SUCCESS';
export const GET_COLLABORATOR_DATA_LIST_ERROR = 'GET_COLLABORATOR_DATA_ERROR';
export const GET_COLLABORATOR_DATA_LIST_CLEAR = 'GET_COLLABORATOR_DATA_CLEAR';
