export const GET_PLAYER_GOAL_BULK_LIST = 'GET_PLAYER_GOAL_BULK_LIST'
export const GET_PLAYER_GOAL_BULK_LIST_SUCCESS = 'GET_PLAYER_GOAL_BULK_LIST_SUCCESS'
export const GET_PLAYER_GOAL_BULK_LIST_ERROR = 'GET_PLAYER_GOAL_BULK_LIST_ERROR'
