export const UPDATE_LEVEL_LIST = 'UPDATE_LEVEL_LIST'
export const UPDATE_LEVEL_LIST_SUCCESS = 'UPDATE_LEVEL_LIST_SUCCESS'
export const UPDATE_LEVEL_LIST_ERROR = 'UPDATE_LEVEL_LIST_ERROR'
export const CLEAR_LEVEL_LIST_UPDATE = 'CLEAR_LEVEL_LIST_UPDATE'