export const UPDATE_TEAM = 'UPDATE_TEAM'
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS'
export const UPDATE_TEAM_ERROR = 'UPDATE_TEAM_ERROR'
export const CLEAR_TEAM_UPDATE = 'CLEAR_TEAM_UPDATE'