export const UPDATE_COACHING_ITEM = 'UPDATE_COACHING_ITEM'
export const UPDATE_COACHING_ITEM_SUCCESS = 'UPDATE_COACHING_ITEM_SUCCESS'
export const UPDATE_COACHING_ITEM_ERROR = 'UPDATE_COACHING_ITEM_ERROR'