export const CREATE_BADGE = 'CREATE_BADGE';
export const CREATE_BADGE_SUCCESS = 'CREATE_BADGE_SUCCESS';
export const CREATE_BADGE_ERROR = 'CREATE_BADGE_ERROR';
export const CLEAR_BADGE_CREATE = 'CLEAR_BADGE_CREATE';
