export const GET_COLLABORATOR_INPUT_LIST = 'GET_COLLABORATOR_INPUT';
export const GET_COLLABORATOR_INPUT_LIST_SUCCESS =
  'GET_COLLABORATOR_INPUT_SUCCESS';
export const GET_COLLABORATOR_INPUT_LIST_ERROR = 'GET_COLLABORATOR_INPUT_ERROR';
export const GET_COLLABORATOR_INPUT_LIST_CLEAR = 'GET_COLLABORATOR_INPUT_CLEAR';
