export const GET_USER_GOAL_LIST = 'GET_USER_GOAL_LIST';
export const GET_USER_GOAL_LIST_SUCCESS = 'GET_USER_GOAL_LIST_SUCCESS';
export const GET_USER_GOAL_LIST_ERROR = 'GET_USER_GOAL_LIST_ERROR';
export const CLEAR_USER_GOAL_LIST = 'CLEAR_USER_GOAL_LIST';
