export const REQUEST_EVOLUTION = 'REQUEST_EVOLUTION';
export const REQUEST_EVOLUTION_SUCCESS = 'REQUEST_EVOLUTION_SUCCESS';
export const REQUEST_EVOLUTION_ERROR = 'REQUEST_EVOLUTION_ERROR';
export const CLEAR_EVOLUTION_REQUEST = 'CLEAR_EVOLUTION_REQUEST';