export const GET_COLLABORATOR_LIST = 'GET_COLLABORATOR_LIST';
export const GET_FREE_COLLABORATOR_LIST = 'GET_FREE_COLLABORATOR_LIST';
export const GET_COLLABORATOR_LIST_SUCCESS = 'GET_COLLABORATOR_LIST_SUCCESS';
export const GET_COLLABORATOR_LIST_ERROR = 'GET_COLLABORATOR_LIST_ERROR';
