export const UPDATE_NOTIFICATION_LIST = 'UPDATE_NOTIFICATION_LIST';
export const UPDATE_NOTIFICATION_LIST_SUCCESS =
  'UPDATE_NOTIFICATION_LIST_SUCCESS';
export const UPDATE_NOTIFICATION_LIST_ERROR = 'UPDATE_NOTIFICATION_LIST_ERROR';
export const CLEAR_NOTIFICATION_LIST_UPDATE = 'CLEAR_NOTIFICATION_LIST_UPDATE';
