export const CREATE_GOAL_ADVICE_LIST = 'CREATE_GOAL_ADVICE_LIST';
export const CREATE_GOAL_ADVICE_LIST_SUCCESS = 'CREATE_GOAL_ADVICE_LIST_SUCCESS';
export const CREATE_GOAL_ADVICE_LIST_ERROR = 'CREATE_GOAL_ADVICE_LIST_ERROR';
export const CLEAR_GOAL_ADVICE_LIST_CREATION = 'CLEAR_GOAL_ADVICE_LIST_CREATION';
