export const GET_GOAL_DEFINITION = 'GET_GOAL_DEFINITION'
export const GET_GOAL_DEFINITION_SUCCESS = 'GET_GOAL_DEFINITION_SUCCESS'
export const GET_GOAL_DEFINITION_ERROR = 'GET_GOAL_DEFINITION_ERROR'
export const CLEAR_GOAL_DEFINITION = 'CLEAR_GOAL_DEFINITION'