export const IMPORT_GOAL_LIST = 'IMPORT_GOAL_LIST';
export const IMPORT_GOAL_LIST_SUCCESS = 'IMPORT_GOAL_LIST_SUCCESS';
export const IMPORT_GOAL_LIST_ERROR = 'IMPORT_GOAL_LIST_ERROR';
export const CLEAR_GOAL_LIST_IMPORT = 'CLEAR_GOAL_LIST_IMPORT';
