export const GET_COLLABORATOR_BADGE_SUMMARY = 'GET_COLLABORATOR_BADGE_SUMMARY';
export const GET_COLLABORATOR_BADGE_SUMMARY_SUCCESS =
  'GET_COLLABORATOR_BADGE_SUMMARY_SUCCESS';
export const GET_COLLABORATOR_BADGE_SUMMARY_ERROR =
  'GET_COLLABORATOR_BADGE_SUMMARY_ERROR';
