export const UPDATE_KPI_LIST = 'UPDATE_KPI_LIST';
export const UPDATE_KPI_LIST_SUCCESS = 'UPDATE_KPI_LIST_SUCCESS';
export const UPDATE_KPI_LIST_ERROR = 'UPDATE_KPI_LIST_ERROR';
export const CLEAR_KPI_LIST_UPDATE = 'CLEAR_KPI_LIST_UPDATE';
