export const GET_COLLABORATOR_CHALLENGE_GOAL_LIST =
  'GET_COLLABORATOR_CHALLENGE_GOAL_LIST';
export const GET_COLLABORATOR_CHALLENGE_GOAL_LIST_SUCCESS =
  'GET_COLLABORATOR_CHALLENGE_GOAL_LIST_SUCCESS';
export const GET_COLLABORATOR_CHALLENGE_GOAL_LIST_ERROR =
  'GET_COLLABORATOR_CHALLENGE_GOAL_LIST_ERROR';
