export const CREATE_WEEK_OVERLAP = 'CREATE_WEEK_OVERLAP';
export const CREATE_WEEK_OVERLAP_SUCCESS = 'CREATE_WEEK_OVERLAP_SUCCESS';
export const CREATE_WEEK_OVERLAP_ERROR = 'CREATE_WEEK_OVERLAP_ERROR';
export const CLEAR_WEEK_OVERLAP_CREATION = 'CLEAR_WEEK_OVERLAP_CREATION';
