export const GET_TEAM_GOAL_DETAIL = 'GET_TEAM_GOAL_DETAIL'
export const GET_TEAM_GOAL_DETAIL_SUCCESS = 'GET_TEAM_GOAL_DETAIL_SUCCESS'
export const GET_TEAM_GOAL_DETAIL_ERROR = 'GET_TEAM_GOAL_DETAIL_ERROR'