export const GET_CATEGORY_ICON_LIST = 'GET_CATEGORY_ICON_LIST'
export const GET_CATEGORY_ICON_LIST_SUCCESS = 'GET_CATEGORY_ICON_LIST_SUCCESS'
export const GET_CATEGORY_ICON_LIST_ERROR = 'GET_CATEGORY_ICON_LIST_ERROR'