export const GET_USABLE_LIST = `GET_USABLE_LIST`;
export const GET_USABLE_LIST_FOR_CATEGORY = `GET_USABLE_LIST_FOR_CATEGORY`;
export const GET_CATEGORY_ICON_LIST_SUCCESS = 'GET_CATEGORY_ICON_LIST_SUCCESS';
export const GET_CATEGORY_ICON_LIST_ERROR = 'GET_CATEGORY_ICON_LIST_ERROR';
