export const CONNECT_AIRCALL = 'CONNECT_AIRCALL';
export const CONNECT_AIRCALL_SUCCESS = 'CONNECT_AIRCALL_SUCCESS';
export const CONNECT_AIRCALL_ERROR = 'CONNECT_AIRCALL_ERROR';
export const CLEAR_AIRCALL_CONNECT = 'CLEAR_AIRCALL_CONNECT';
