export const GET_COACHING_ITEM_LIST = 'GET_COACHING_ITEM_LIST'
export const GET_COACHING_ITEM_LIST_SUCCESS = 'GET_COACHING_ITEM_LIST_SUCCESS'
export const GET_COACHING_ITEM_LIST_ERROR = 'GET_COACHING_ITEM_LIST_ERROR'