export const GET_NEXT_PERIOD_LIST = 'GET_NEXT_PERIOD_LIST';
export const GET_NEXT_PERIOD_LIST_SUCCESS = 'GET_NEXT_PERIOD_LIST_SUCCESS';
export const GET_NEXT_PERIOD_LIST_ERROR = 'GET_NEXT_PERIOD_LIST_ERROR';
