export const UPDATE_NEWS_FEED = 'UPDATE_NEWS_FEED';
export const UPDATE_NEWS_FEED_SUCCESS = 'UPDATE_NEWS_FEED_SUCCESS';
export const UPDATE_NEWS_FEED_ERROR = 'UPDATE_NEWS_FEED_ERROR';
export const UPDATE_NEWS_FEED_CLEAR = 'UPDATE_NEWS_FEED_CLEAR';
