export const UPDATE_CHALLENGE_TYPE_LIST = 'UPDATE_CHALLENGE_TYPE_LIST';
export const UPDATE_CHALLENGE_TYPE_LIST_SUCCESS =
  'UPDATE_CHALLENGE_TYPE_LIST_SUCCESS';
export const UPDATE_CHALLENGE_TYPE_LIST_ERROR =
  'UPDATE_CHALLENGE_TYPE_LIST_ERROR';
export const CLEAR_CHALLENGE_TYPE_LIST_UPDATE =
  'CLEAR_CHALLENGE_TYPE_LIST_UPDATE';
