export const GET_TEAM_GROUP_LIST = 'GET_TEAM_GROUP_LIST';
export const GET_TEAM_GROUP_LIST_SUCCESS = 'GET_TEAM_GROUP_LIST_SUCCESS';
export const GET_TEAM_GROUP_LIST_ERROR = 'GET_TEAM_GROUP_LIST_ERROR';
