export const GET_TEAM_PLAYER_GOAL_LIST = 'GET_TEAM_PLAYER_GOAL_LIST';
export const GET_TEAM_PLAYER_GOAL_LIST_SUCCESS =
  'GET_TEAM_PLAYER_GOAL_LIST_SUCCESS';
export const GET_TEAM_PLAYER_GOAL_LIST_ERROR =
  'GET_TEAM_PLAYER_GOAL_LIST_ERROR';
