export const GET_REWARD_CATEGORY = 'GET_REWARD_CATEGORY';
export const GET_REWARD_CATEGORY_SUCCESS = 'GET_REWARD_CATEGORY_SUCCESS';
export const GET_REWARD_CATEGORY_ERROR = 'GET_REWARD_CATEGORY_ERROR';
