export const UPDATE_BADGE = 'UPDATE_BADGE';
export const UPDATE_BADGE_SUCCESS = 'UPDATE_BADGE_SUCCESS';
export const UPDATE_BADGE_ERROR = 'UPDATE_BADGE_ERROR';
export const CLEAR_BADGE_UPDATE = 'CLEAR_BADGE_UPDATE';
