export const GET_COLLABORATOR_BADGE_LEVEL_LIST =
  'GET_COLLABORATOR_BADGE_LEVEL_LIST';
export const GET_COLLABORATOR_NEXT_BADGE_LEVEL_LIST =
  'GET_COLLABORATOR_NEXT_BADGE_LEVEL_LIST';
export const GET_COLLABORATOR_BADGE_LEVEL_LIST_SUCCESS =
  'GET_COLLABORATOR_BADGE_LEVEL_LIST_SUCCESS';
export const GET_COLLABORATOR_BADGE_LEVEL_LIST_ERROR =
  'GET_COLLABORATOR_BADGE_LEVEL_LIST_ERROR';
