export const GET_CHALLENGE_SUMMARY = 'GET_CHALLENGE_SUMMARY';
export const GET_CHALLENGE_SUMMARY_SUCCESS = 'GET_CHALLENGE_SUMMARY_SUCCESS';
export const GET_CHALLENGE_SUMMARY_ERROR = 'GET_CHALLENGE_SUMMARY_ERROR';
export const GET_CHALLENGE_SUMMARY_CLEAR = 'GET_CHALLENGE_SUMMARY_CLEAR';
