export const REMOVE_BADGE_LEVEL = 'REMOVE_BADGE_LEVEL'
export const REMOVE_BADGE_LEVEL_SUCCESS = 'REMOVE_BADGE_LEVEL_SUCCESS'
export const REMOVE_BADGE_LEVEL_ERROR = 'REMOVE_BREMOVE_BADGE_LEVEL_ERRORADGE_LEVEL'