export const GET_TEAM_CHALLENGE_DETAIL = 'GET_TEAM_CHALLENGE_DETAIL';
export const GET_TEAM_CHALLENGE_DETAIL_SUCCESS = 'GET_TEAM_CHALLENGE_DETAIL_SUCCESS';
export const GET_TEAM_CHALLENGE_DETAIL_ERROR = 'GET_TEAM_CHALLENGE_DETAIL_ERROR';