export const GET_BADGE_LEVEL_LIST = 'GET_BADGE_LEVEL_LIST'
export const GET_BADGE_LEVEL_LIST_SUCCESS = 'GET_BADGE_LEVEL_LIST_SUCCESS'
export const GET_BADGE_LEVEL_LIST_ERROR = 'GET_BADGE_LEVEL_LIST_ERROR'