export const CREATE_BADGE_LEVEL_LIST = 'CREATE_BADGE_LEVEL_LIST';
export const CREATE_BADGE_LEVEL_LIST_SUCCESS =
  'CREATE_BADGE_LEVEL_LIST_SUCCESS';
export const CREATE_BADGE_LEVEL_LIST_ERROR = 'CREATE_BADGE_LEVEL_LIST_ERROR';
export const CLEAR_BADGE_LEVEL_LIST_CREATION =
  'CLEAR_BADGE_LEVEL_LIST_CREATION';
