export const GET_CHALLENGE_DETAIL = 'GET_CHALLENGE_DETAIL';
export const GET_CHALLENGE_DETAIL_SUCCESS = 'GET_CHALLENGE_DETAIL_SUCCESS';
export const GET_CHALLENGE_DETAIL_ERROR = 'GET_CHALLENGE_DETAIL_ERROR';