export const DELETE_NEWS_FEED_COMMENT = 'DELETE_NEWS_FEED_COMMENT';
export const DELETE_NEWS_FEED_COMMENT_SUCCESS =
  'DELETE_NEWS_FEED_COMMENT_SUCCESS';
export const DELETE_NEWS_FEED_COMMENT_ERROR = 'DELETE_NEWS_FEED_COMMENT_ERROR';
export const DELETE_NEWS_FEED_COMMENT_CLEAR = 'DELETE_NEWS_FEED_COMMENT_CLEAR';
