export const GET_USER_GOAL_DETAIL = 'GET_USER_GOAL_DETAIL'
export const GET_USER_GOAL_DETAIL_SUCCESS = 'GET_USER_GOAL_DETAIL_SUCCESS'
export const GET_USER_GOAL_DETAIL_ERROR = 'GET_USER_GOAL_DETAIL_ERROR'