export const CREATE_TEAM_GROUP = 'CREATE_TEAM_GROUP';
export const CREATE_TEAM_GROUP_SUCCESS = 'CREATE_TEAM_GROUP_SUCCESS';
export const CREATE_TEAM_GROUP_ERROR = 'CREATE_TEAM_GROUP_ERROR';
export const CLEAR_TEAM_GROUP_CREATION = 'CLEAR_TEAM_GROUP_CREATION';
