name: Build and deploy Create React App to Azure Web App - testfgpub

on:
  push:
    branches:
      - develop-spider-cicd
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --legacy-peer-deps

      - name: Build the application
        env:
          CI: false  # Désactiver le traitement des avertissements comme des erreurs
        run: yarn build

      - name: Zip build artifact
        run: zip -r build.zip build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Unzip build artifact
        run: unzip build.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'testfgpub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_011F37D6514F44778BD232C544B25655 }}
          package: build
