name: Build and deploy Front (DEV/PREPROD)

on:
  push:
    branches:
      - develop-spider-cicd
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --legacy-peer-deps

      - name: Build the application
        env:
          CI: false
        run: yarn build

      - name: Zip build artifact
        run: zip -r build.zip build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build.zip

      - name: Create new tag
        run: |
          chmod +x ./create-tag.sh
          ./create-tag.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_objow_front_edenred_preprod:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'preprod'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Unzip build artifact
        run: unzip build.zip

      - name: Deploy to Azure Web App - objow-front-edenred-preprod
        id: deploy-to-webapp-front-preprod
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'objow-front-preprod'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_OBJOW_PREPROD }}
          package: build

  deploy_objow_front_edenred_dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-webapp-edenred.outputs.webapp-url }}

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: Unzip build artifact
        run: unzip build.zip

      - name: Deploy to Azure Web App - objow-front-edenred-dev
        id: deploy-to-webapp-objow
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'objow-front-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_OBJOW_DEV }}
          package: build
