export const UPDATE_NEWS_FEED_COMMENT = 'UPDATE_NEWS_FEED_COMMENT';
export const UPDATE_NEWS_FEED_COMMENT_SUCCESS =
  'UPDATE_NEWS_FEED_COMMENT_SUCCESS';
export const UPDATE_NEWS_FEED_COMMENT_ERROR = 'UPDATE_NEWS_FEED_COMMENT_ERROR';
export const UPDATE_NEWS_FEED_COMMENT_CLEAR = 'UPDATE_NEWS_FEED_COMMENT_CLEAR';
